name: Generate GitHub Stats Images

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day at midnight UTC
  workflow_dispatch:        # lets you trigger it manually anytime

jobs:
  generate-images:
    runs-on: ubuntu-latest
    steps:
      - name: Generate stats images
        uses: jstrieb/github-stats@master
        with:
          username: the-zoomeee
          exclude_repos: ""
          exclude_langs: ""
          include_all_commits: true
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
